### ISSUE TITLE
nextPageUrl always uses "query" as parameter name

### ISSUE THREAD

**Issue by enkay** [laravel/scout#209] opened 2017-07-12 05:47 UTC
When using the paginate method, the nextPageUrl always uses "query" as the parameter name for the search query instead of using the value in the request.

**Comment by nikugogoi** [comment] 2018-01-19 12:35
I checked the vendor files and there is indeed a parameter "query" appended. The value of the "query" parameter is the search term used in scout. 
I dont know why they have implemented this. Parameters can be appended using `appends()` method of the paginated instance. Would really like to know the reason behind this feature and if there is a way to disable the same.
by the way, you could use the same query parameter in the scout search() method as `App\someModel::search(request('query'))->paginate()` and so you only have the option of using 'query' as the parameter for searching in scout
Let me know if you found out any answers

**Comment by driesvints** [comment] 2018-10-05 08:54
Closing this because it's a duplicate of #58. Let's continue discussion there.

**Closed by driesvints** 2018-10-05 08:54 UTC
