### ISSUE TITLE
[Algolia] Invalid syntax for numeric condition:status=open

### ISSUE THREAD

**Issue by yueyuzhao** [laravel/scout#831] opened 2024-05-13 13:02 UTC
### Scout Version

10.9.0

### Scout Driver

Algolia

### Laravel Version

11.7

### PHP Version

8.2.17

### Description

Invalid syntax for numeric condition:status=open {"exception":"[object] (Algolia\\AlgoliaSearch\\Exceptions\\BadRequestException(code: 400): Invalid syntax for numeric condition:status=open at /xxxx/vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:221)

```
Array
(
    [body] => Array
        (
            [numericFilters] => Array
                (
                    [0] => Array
                        (
                            [0] => status=open
                            [1] => status=paid
                        )

                )

            [hitsPerPage] => 15
            [page] => 0
            [query] => 
        )

    [headers] => Array
        (
            [X-Algolia-Application-Id] => xxxxxx
            [X-Algolia-API-Key] => xxxxxx
            [User-Agent] => Algolia for PHP (3.4.1); PHP (8.2.17); Guzzle (7); Laravel Scout (10.9.0)
            [Content-Type] => application/json
        )

    [method] => POST
    [query] => Array
        (
        )

    [retryNumber] => 1
    [host] => https://xxxxx-dsn.algolia.net/1/indexes/dev_order_index/query
)
```

The input filters are placed in `numericFilters`, but those are not numeric values, and should be place in `filters` as `status:open OR status:paid`

### Steps To Reproduce

1. use algolia engine
2. create an index
3. search with `whereIn` described in https://laravel.com/docs/11.x/scout#where-clauses

**Comment by yueyuzhao** [comment] 2024-05-13 13:08
For those who want to search with filters, you can set filters by `options` as:
```php
$orders = Order::search('Star Trek')->options([
    'filters' => 'status:open OR status:paid',
])->get();
```

**Comment by driesvints** [comment] 2024-05-13 13:43
Could you share an exact code sample to reproduce this?

**Comment by yueyuzhao** [comment] 2024-05-13 22:12
@driesvints 
1. Set the engine to algolia
2. Set `User` model searchable (or any searchable model)
3. Put the following code to your `routes/console.php`
4. Run `php artisan scout-where-in`
```php
// ......
use App\Models\User;
// ......

Artisan::command('scout-where-in', function () {
    User::search('hi')
        ->whereIn('status', ['open', 'paid'])
        ->get();
});

```
And you will get 
```

  Algolia\AlgoliaSearch\Exceptions\BadRequestException 

  Invalid syntax for numeric condition:status=open

  at vendor/algolia/algoliasearch-client-php/src/RetryStrategy/ApiWrapper.php:221
    217▕ 
    218▕         if (404 == $statusCode) {
    219▕             throw new NotFoundException($responseArray['message'], $statusCode);
    220▕         } elseif ($statusCode >= 400) {
  ➜ 221▕             throw new BadRequestException($responseArray['message'], $statusCode);
    222▕         } elseif (2 != (int) ($statusCode / 100)) {
    223▕             throw new AlgoliaException($statusCode.': '.$body, $statusCode);
    224▕         }
    225▕ 

      +7 vendor frames 

  8   routes/console.php:9
      Laravel\Scout\Builder::get()
      +13 vendor frames 

  22  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))

```

**Comment by driesvints** [comment] 2024-05-17 10:06
I'm so confused. This indeed can't ever work how it's implemented right now but has been around for like 8 years already. I can't believe we never caught this before...

**Comment by driesvints** [comment] 2024-05-17 10:18
Hah, I originally documented this 😂 https://github.com/laravel/docs/pull/7550

I guess I misunderstood how this worked in Algolia. However, we can't change the docs since meilisearch and other engines now work this way. I feel like we should update the AlgoliaEngine to use `filters` instead of `numericFilters`. The Algolia docs also say this should be used preferable: https://www.algolia.com/doc/api-reference/api-parameters/numericFilters/

<img width="732" alt="Screenshot 2024-05-17 at 12 12 01" src="https://github.com/laravel/scout/assets/594614/64f2e560-71d0-4f47-bb1f-c34fa2d68812">

The refactored code to `filters` should behave the same as in the code example from `numericFilters` below:

<img width="741" alt="Screenshot 2024-05-17 at 12 18 12" src="https://github.com/laravel/scout/assets/594614/fcc29825-b13e-45b8-8d1a-2ceaab3f2ddf">

**Comment by Boorinio** [comment] 2024-06-12 13:06
@driesvints  are we going to close this issue now?
https://github.com/laravel/scout/pull/837

**Comment by driesvints** [comment] 2024-06-18 16:34
Going to close this one now but would like the PR from @Boorinio to be sent to 11.x instead. Thanks!

**Closed as completed by driesvints** 2024-06-18 16:34 UTC
Labels: help wanted

**Comment by Boorinio** [comment] 2024-06-18 19:09
Made a pr for 11.x
https://github.com/laravel/scout/pull/839
