### ISSUE TITLE
Abstract method `performSearch` and `deleteIndex` are not implemented

### ISSUE THREAD

**Issue by alies-dev** [laravel/scout#883] opened 2024-11-13 08:45 UTC
### Scout Version

10.11.6

### Scout Driver

Algolia

### Laravel Version

11.31.0

### PHP Version

8.3.10

### Description

Update updating to the [v10.11.6](https://github.com/laravel/scout/compare/v10.11.5...v10.11.6) I've got this error:

```
Class Algolia\ScoutExtended\Engines\AlgoliaEngine contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Laravel\Scout\Engines\AlgoliaEngine::performSearch, Laravel\Scout\Engines\AlgoliaEngine::deleteIndex)
```

Additional packages I use:
```
"algolia/algoliasearch-client-php": "^3.4.1",
"algolia/scout-extended": "^3.1",
```

### Steps To Reproduce

-

**Comment by crynobone** [comment] 2024-11-13 09:46
I believe `algolia/scout-extended` should use it's own `AlgoliaEngine` class instead of relying from `laravel/scout`. Duplicate of https://github.com/algolia/scout-extended/issues/347

**Closed as completed by crynobone** 2024-11-13 09:46 UTC
