### ISSUE TITLE
scout:flush command doesn't flush/remove anything?

### ISSUE THREAD

**Issue by bbashy** [laravel/scout#101] opened 2016-10-12 10:42 UTC
It seems `scout:flush` doesn't seem to do anything. Deleting a record from the database manually then doing `scout:flush` and/or `scout:import` doesn't remove the old record.

**Comment by AlexCatch** [comment] 2016-12-20 14:41
I can confirm this, doing flush with ElasticSearch doesn't work.

**Comment by sebestenyb** [comment] 2017-03-09 23:34
Neither with [TNTSearch](https://github.com/teamtnt/laravel-scout-tntsearch-driver)

**Comment by bbashy** [comment] 2017-03-09 23:40
Solution was to just do a cURL DELETE request to ES but who wants to do that when you have artisan commands.

**Comment by JackWH** [comment] 2017-04-23 14:18
I've been unable to get flushing to work with Algolia either.

**Comment by LoganLehman** [comment] 2017-05-05 19:22
@taylorotwell Any news?

**Comment by aurawindsurfing** [comment] 2017-05-22 11:36
Hi, I confirm that:
`php artisan scout:flush "App\Classified"
All [App\Classified] records have been flushed.`
does nothing to algolia index.

**Comment by LoganLehman** [comment] 2017-07-13 18:28
Ping again?

**Comment by giacomodeglinnocenti** [comment] 2017-07-16 16:01
Same issue here on fresh Laravel 5.4

**Comment by eithed** [comment] 2017-07-18 10:02
On my fresh install while flush removes entries that exist, it doesn't remove entries that do not

**Comment by julienbourdeau** [comment] 2017-07-18 11:33
I think the `scout:flush` command doest clear the index but instead, it removes items by ID.

Is it possible that the id you have in database are not the same as the one you have in your search index?

This happens when you seed your DB, import, trunctate your table and seed again. At this point, if you flush, it won't remove anything.

**Comment by eithed** [comment] 2017-07-18 12:06
Yup - that's exactly the case, as reported by OP; it "works", but you'd expect flush to empty all entries, as after truncating the DB it won't be possible to get rid of them without resorting to deleting the entire index.

**Comment by IllyaMoskvin** [comment] 2017-07-27 14:51
Seconding @julienbourdeau. Thanks for the suggestion to check ids, they were the cause of our issue as well! Our situation was a little different. Sharing the details for posterity, just in case someone is using a similar approach:

We are using a custom Solr Scout engine, and we were indexing all `Searchable` models into one core (storing a common set of fields). We couldn't use the models' primary keys to track them in the index, since that would cause collisions among different models, so we assigned them string keys namespaced with the model's classname. We forgot to update the `delete()` method in our `SolrScoutEngine` to account for this transformation. Everything fixed itself once we applied the same transformation there.

**For troubleshooting:** check if `$model->unsearchable` and `$model::removeAllFromSearch()` are working. Check if the `$model` instance gets removed from the index when you issue an Eloquent delete or destroy command. If that's not working, review the `delete()` method in your Scout engine to ensure you are passing the correct ids.

**Comment by hammy4785** [comment] 2017-09-27 15:45
So is there a possibility of having a command created or changed so it can clear all regardless of id

**Comment by julienbourdeau** [comment] 2017-09-27 16:07
If we want to do it right, it implies to add a public `clear()` method in each engine implementation, so adding it to the abstract class but it would break backward compatibility.

But you can define your own, I just made one for Algolia: https://gist.github.com/julienbourdeau/c5b3adc369da2e5e02527de3cb73ee6c

**Comment by driesvints** [comment] 2018-10-05 13:43
I can see this being useful. I'll try to send something in for this for the next major version.

**Comment by driesvints** [comment] 2018-10-05 15:34
Sent in a PR. Please provide feedback if possible: https://github.com/laravel/scout/pull/310

**Comment by driesvints** [comment] 2018-10-08 13:58
PR just got merged. Will be in the next major release of Scout.

**Closed by driesvints** 2018-10-08 13:58 UTC
Labels: Action Needed
