### ISSUE TITLE
scout:import performance issues when toSearchableArray contains relationships

### ISSUE THREAD

**Issue by bkilshaw** [laravel/scout#329] opened 2018-11-30 17:02 UTC
I recently made a model Searchable using Scout and Algolia. When running scout:import in production the whole production (Google App Engine) crashed. There was just over 15K records that needed to import. The SQL queries were going out of control (2000-2500 queries/second) and our production environment was down until the queued jobs all failed.

Someone in Discord (@fitztrev) mentioned that they ran into the same issue and tracked it down to the lack of eager loading of relationships mentioned in toSearchableArray(). Here is the method in my case:

```
public function toSearchableArray()
    {
        return [
            'provider_user_id' => $this->provider_user_id,
            'provider_name' => $this->provider->display_name,
            'receiver_user_id' => $this->receiver_user_id,
            'receiver_name' => $this->receiver->display_name,
            'receiver_hierarchy' => $this->receiver->role->hierarchy,
            'store_id' => $this->receiver->store_id,
            'category_id' => $this->category_id,
            'category_name' => $this->category->name,
            'subcategory_id' => $this->subcategory_id,
            'subcategory_name' => $this->subcategory->name,
            'comments' => $this->comments,
            'date_occurred'=> $this->date_occurred
        ];
    }
```
If the relationships aren't eager loaded it would make sense that this would generate an obscene number of queries.

I believe I could use `protected $with = ['provider', 'receiver', 'category', 'subcategory'];`  on the object, but that would mean I'm eager loading the relationships every single time I have an instance of this object, which I don't always want/need to do.

**Comment by fitztrev** [comment] 2018-12-04 16:38
Cross ref algolia/scout-extended#90

**Comment by driesvints** [comment] 2018-12-10 16:41
Did some research for this. The problem is indeed that the `makeAllSearchable` builds up a new query. Using `protected $with` would indeed solve this problem but can't be done for the reason stated above. We could solve this with an extra method on the `Searchable` trait. Something like this (or a better name):

```php
public function searchableWith(): array
{
    return ['provider', 'receiver', 'category', 'subcategory'];
}
```

Which then would be used in the `makeAllSearchable` method. I think this would be the only solution for this and still an appropriate one because like you stated yourself you'd only use this when doing an import. For all other purposes you'd do the eager loading beforehand.

**Comment by driesvints** [comment] 2018-12-10 16:41
Gonna mark this as a feature request rather than a bug because the temp solution would indeed be to use the `with` property.

**Comment by terryBaz** [comment] 2019-01-04 17:14
for now you could just override `makeAllSearchable()` in your model (the model that is been indexed by scout) so you get something like that ( scout version "laravel/scout": "5.0.*" ) : 

```
/**
 * Make all instances of the model searchable.
 *
 * @return void
 */
public static function makeAllSearchable()
{
    $self = new static();

    $softDeletes = in_array(SoftDeletes::class, class_uses_recursive(get_called_class())) &&
        config('scout.soft_delete', false);

    $self->newQuery()
        ->with([
            //your relations goes here
        ])
        ->when($softDeletes, function ($query) {
            $query->withTrashed();
        })
        ->orderBy($self->getKeyName())
        ->searchable();
}
```

**Comment by clovenlife** [comment] 2019-02-12 15:37
I was able to resolve the efficiency issue by creating a global scope with all the relations. The downside is that I have no way to disable global scopes when doing a search

**Comment by altynbek07** [comment] 2020-05-05 01:06
> for now you could just override `makeAllSearchable()` in your model (the model that is been indexed by scout) so you get something like that :
> 
> ```
> /**
>  * Make all instances of the model searchable.
>  *
>  * @return void
>  */
> public static function makeAllSearchable()
> {
>     $self = new static();
> 
>     $softDeletes = in_array(SoftDeletes::class, class_uses_recursive(get_called_class())) &&
>         config('scout.soft_delete', false);
> 
>     $self->newQuery()
>         ->with([
>             /*******************************
>                your relations goes here
>            *******************************/
>         ])
>         ->when($softDeletes, function ($query) {
>             $query->withTrashed();
>         })
>         ->orderBy($self->getKeyName())
>         ->searchable();
> }
> ```
> 
> > scout version "laravel/scout": "5.0.*"

But it is not work when queue is true.

**Comment by driesvints** [comment] 2020-06-22 14:34
Closing this since the PR was rejected. We probably won't be pursuing this any further.

**Closed by driesvints** 2020-06-22 14:34 UTC
Labels: enhancement
